CTS converstion and EpiDoc work tlg1286
OpenGreekAndLatin/First1KGreek pull request #2292
Opened 2020-11-02 21:18 UTC by charhoughton

CTS and EpiDoc work on tlg1286.tlg001 through tlg1286.tlg020, except tlg1286.tlg015.

2020-11-02 21:32 UTC, ahanhardt commented
fix #2259

2020-11-03 21:48 UTC, lcerrato commented
For these works, the spreadsheet has a different workgroup and different work titles. 
It's preferable to follow the spreadsheet (which is the TLG), so the workgroup is not Hermetica, but Corpus Hermeticum, and the work titles in the metadata should follow those examples. 

I am verifying this presently.

For instance, Poimandres is the work title for tlg1286.tlg001.

Also, the book title is not **Hermetica Vol One** but as it reads on the page:
**Hermetica. The Ancient Greek and Latin Writings which Contain Religious or Philosophic Teachings Ascribed to Hermes Trismegistus, Vol. I.**

2020-11-03 21:58 UTC, lcerrato requested changes

2020-11-03 21:58 UTC, lcerrato commented on data/tlg1286/tlg001/tlg1286.tlg001.1st1K-grc1.xml
> +               <author>Hermes Trimegistus</author>
Probably should be Corpus Hermeticum, but if kept as is, there is an "s" missing in the name.

2020-11-03 21:58 UTC, lcerrato commented on data/tlg1286/tlg001/tlg1286.tlg001.1st1K-grc1.xml
> +                       <title xml:lang="lat">Hermetica Vol One</title>
Preferred title is 
Hermetica. The Ancient Greek and Latin Writings which Contain Religious or Philosophic Teachings Ascribed to Hermes Trismegistus.

Then the volume is indicated later in this header, not here.

2020-11-03 21:58 UTC, lcerrato commented on data/tlg1286/tlg001/tlg1286.tlg001.1st1K-grc1.xml
> +                   </monogr>
This is where the volume is indicated (following the `</imprint>` tag
`<biblScope unit="volume">1</biblScope>`

2020-11-03 21:58 UTC, lcerrato commented on data/tlg1286/tlg001/tlg1286.tlg001.1st1K-grc1.xml
> +           <change when="2020-02-02" who="Jane Smith">initial markup of new file.</change>
Is this a placeholder tag?

2020-11-03 22:05 UTC, lcerrato commented
@charhoughton @ahanhardt 

Thanks for this!

Please hold off for now as I am trying to work this and make an example of the first file.

There are a few issues here with titles, group name, author name, etc. These need a thorough review, but I am waiting on feedback.
The book title definitely needs revision in all of the cts metadata as well as the files themselves, and we have a separate tag to indicate volume.
I also see a "Jane Smith" in the change log which I believe is a placeholder?
In general, let's try to clean up the indentation a bit as this helps with my review tremendously.

I will try to make changes as I go, but this is a big pull request, so this is where having lots of files in one pull request doesn't work well as I have a few points in each file.

On first look, these are failing on a few points. We have a misnamed metadata file (__cts__ .xml  has an extra space ), some misnamed files ( urn.cts.greekLit.tlg1286.tlg004.1st1K-grc1.xml, | urn.cts.greekLit.tlg1286.tlg008.1st1K-grc1.xml) etc. So I have go through this little by little. Also note that there are unacceptable sections in tlg1286.tlg020.1st1K-grc.xml
https://travis-ci.org/github/OpenGreekAndLatin/First1KGreek/builds/740994284

I'm still trying to figure out the best approach so don't make any local changes until I can get the naming confirmed.

2020-11-03 22:12 UTC, lcerrato commented on data/tlg1286/tlg001/tlg1286.tlg001.1st1K-grc1.xml
> +                    <p rend="merge">
`<p rend="merge">` not used. Simple `<p>` suffices when indentation is not used.

2020-11-09 16:48 UTC, lcerrato approved these changes

2020-11-09 16:50 UTC, merged

2020-11-09 16:57 UTC, lcerrato commented
@charhoughton @ahanhardt 
Thank you for all of the work on this batch. I know they were challenging files!