tlg0555.tlg001-tlg0555.tlg007
OpenGreekAndLatin/First1KGreek pull request #2386
Opened 2021-05-12 14:39 UTC by AlisonBabeu

Updated the cts.xml files to current standards
Updated the bibliographic metadata as well

2021-05-12 17:20 UTC, lcerrato requested changes
`<title>Protrepticus und Paedagogus</title>` should probably have a "mul" language attribute

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg001/tlg0555.tlg001.opp-grc1.xml
> +           <series>
`<title>Protrepticus und Paedagogus</title>` (above) should probably have a "mul" language attribute

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg002/tlg0555.tlg002.opp-grc1.xml
>  							<date>1905</date>
see previous comment

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg004b/tlg0555.tlg004b.opp-grc1.xml
> +						<title>Stromata, Buch VII-VIII. Excerpta ex Theodoto. Eclogae prophetica.</title>
should probably have a "mul" language attribute as it is German and Latin.

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg005/tlg0555.tlg005.opp-grc1.xml
> +						<title>Stromata, Buch VII-VIII. Excerpta ex Theodoto. Eclogae prophetica.</title>
same

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg006/__cts__.xml
> +    <ti:description xml:lang="lat">Clement of Alexandria.  Clemens Alexandrinus, Volume 3. Stählin, Otto, editor. Leipzig: Hinrichs, 1909.</ti:description>
change language from "lat" to "mul"

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg006/tlg0555.tlg006.opp-grc1.xml
> +						<title>Stromata, Buch VII-VIII. Excerpta ex Theodoto. Eclogae prophetica.</title>
same

2021-05-12 17:20 UTC, lcerrato commented on data/tlg0555/tlg006/tlg0555.tlg006.opp-grc1.xml
> +						<title level="s">Clemens Alexandrinus
should be "lat" title attribute

2021-05-12 17:22 UTC, lcerrato commented
@AlisonBabeu 
I would just double check the titles in the files — most appear to be either a combination of Latin and German or Latin, so we probably want some language attributes there.  I don't think I flagged them all because the edited portions of the files weren't always visible.
One of the metadata files had a "lat" where a "mul" belonged, but the editions are where I spotted the missing info.

2021-05-13 19:32 UTC, AlisonBabeu commented
hi @lcerrato I will make those changes! Thanks for reviewing!

2021-08-19 20:27 UTC, lcerrato approved these changes

2021-08-20 15:54 UTC, merged